import type { SalesTool, CategoryMeta } from "./types"

export const tools: SalesTool[] = [
  // ── Prospecting ──────────────────────────────────────────────
  {
    slug: "apollo",
    name: "Apollo.io",
    oneLiner: "Sales intelligence and engagement platform with a massive B2B contact database.",
    description:
      "Apollo.io provides a REST API that gives developers programmatic access to over 275 million verified contacts and 60 million companies. Build prospecting workflows, enrich leads in real time, and sync data directly into your CRM. The API supports advanced search filters, email sequencing, and engagement tracking, making it ideal for teams that want to automate top-of-funnel pipeline generation.",
    category: "Prospecting",
    logoUrl: "/logos/apollo.svg",
    websiteUrl: "https://www.apollo.io",
    docsUrl: "https://apolloio.github.io/apollo-api-docs/",
    pricingUrl: "https://www.apollo.io/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/apollo-io/mcp-server",
        label: "Community MCP Server",
        mcpConfig: '{\n  "mcpServers": {\n    "apollo": {\n      "command": "npx",\n      "args": ["-y", "@apollo/mcp-server"],\n      "env": {\n        "APOLLO_API_KEY": "YOUR_API_KEY"\n      }\n    }\n  }\n}',
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js"],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Search 275M+ Contacts", "Enrich Lead Lists", "Automate Sequences"],
    aiDifficulty: "Beginner-Friendly",
    starterPrompt: "Claude, search Apollo for 10 Sales Managers at US-based Series B startups and save them to my list.",
    mcpReady: true,
    isFeatured: true,
    alternativeTo: ["ZoomInfo", "Lusha", "Cognism"],
  },
  {
    slug: "clay",
    name: "Clay",
    oneLiner: "Creative data enrichment and outbound automation platform.",
    description:
      "Clay's REST API lets you programmatically run waterfall enrichment across 100+ data providers, build dynamic lead lists, and orchestrate personalized outbound campaigns. It acts as a universal connector between data sources so you can enrich any prospect record with firmographic, technographic, and intent signals. Clay is a go-to tool for revenue teams building highly targeted, data-driven outreach at scale.",
    category: "Prospecting",
    logoUrl: "/logos/clay.svg",
    websiteUrl: "https://www.clay.com",
    docsUrl: "https://docs.clay.com",
    pricingUrl: "https://www.clay.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Waterfall Enrichment", "AI-Powered Outbound", "Universal Data Connector"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, use Clay to enrich this list of domains with their latest funding round and LinkedIn URL.",
    mcpReady: false,
    isFeatured: true,
    alternativeTo: ["Apollo.io", "ZoomInfo", "Clearbit"],
  },
  {
    slug: "prospeo",
    name: "Prospeo",
    oneLiner: "Email finder and verification API for sales prospecting.",
    description:
      "Prospeo offers a straightforward REST API for finding and verifying professional email addresses at scale. Use the email finder to locate contacts by name and domain, run bulk verification to clean your lists, and extract emails from LinkedIn profiles. Prospeo is designed for lean sales teams and developers who need reliable email discovery without the overhead of a full-suite platform.",
    category: "Prospecting",
    logoUrl: "/logos/prospeo.svg",
    websiteUrl: "https://prospeo.io",
    docsUrl: "https://prospeo.io/api/documentation",
    pricingUrl: "https://prospeo.io/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    aiCapabilities: ["Email Finding", "Email Verification", "LinkedIn Data Extraction"],
    aiDifficulty: "Beginner-Friendly",
    starterPrompt: "Claude, find the professional email for the CEO of Stripe using Prospeo.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Hunter.io", "Snov.io"],
  },
  {
    slug: "kaspr",
    name: "Kaspr",
    oneLiner: "LinkedIn-first B2B contact data retrieval and prospecting tool.",
    description:
      "Kaspr provides a developer API that allows programmatic access to its massive database of business and contact information. Developers can retrieve verified names, email addresses, and phone numbers directly from LinkedIn profiles. The API is designed for building custom prospecting workflows and keeping your CRM data up-to-date with high-accuracy contact details.",
    category: "Prospecting",
    logoUrl: "/logos/kaspr.svg",
    websiteUrl: "https://www.kaspr.io",
    docsUrl: "https://developer.kaspr.io",
    pricingUrl: "https://www.kaspr.io/pricing",
    apiType: ["REST"],
    authMethod: ["Bearer Token"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    aiCapabilities: ["Enrich LinkedIn Leads", "Retrieve Verified Emails", "Find Mobile Numbers"],
    aiDifficulty: "Beginner-Friendly",
    starterPrompt: "Claude, use Kaspr to find the mobile phone number for this LinkedIn profile URL.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Lusha", "Apollo.io", "Cognism"],
  },
  {
    slug: "cognism",
    name: "Cognism",
    oneLiner: "Global B2B sales intelligence with premium mobile data.",
    description:
      "Cognism offers a robust API for searching, previewing, and enriching contact and account data from its globally compliant database. It is especially strong in European markets and provides 'Diamond Data'—phone-verified mobile numbers. The API supports deep enrichment and intent-based prospecting, allowing developers to build sophisticated outbound systems that target the right buyers at the right time.",
    category: "Prospecting",
    logoUrl: "/logos/cognism.svg",
    websiteUrl: "https://www.cognism.com",
    docsUrl: "https://cognism.com/api-docs",
    pricingUrl: "https://www.cognism.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Global Data Enrichment", "Intent-Based Prospecting", "Verified Mobile Data"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, search Cognism for companies in the UK using Salesforce and get their VP of Sales contact info.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["ZoomInfo", "Apollo.io", "Lusha"],
  },
  {
    slug: "crawl4ai",
    name: "Crawl4AI",
    oneLiner: "Open-source LLM-friendly web crawler and scraper.",
    description:
      "Crawl4AI is an open-source Python library designed to crawl websites and convert them into clean, structured Markdown for Large Language Models. It features stealth mode to avoid bot detection, session management for complex workflows, and the ability to extract structured data using LLMs. It is a favorite among AI-native operators for 'automated website verification' and researching thousands of company pages at once.",
    category: "Prospecting",
    logoUrl: "/logos/crawl4ai.svg",
    websiteUrl: "https://crawl4ai.com",
    docsUrl: "https://crawl4ai.com/docs",
    pricingUrl: "https://github.com/unclecode/crawl4ai",
    githubUrl: "https://github.com/unclecode/crawl4ai",
    apiType: ["REST"],
    authMethod: ["None"],
    integrations: [
      {
        platform: "Custom",
        url: "https://github.com/unclecode/crawl4ai",
        label: "Python SDK",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Python"],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    aiCapabilities: ["Web Scraping for LLMs", "Structured Data Extraction", "Automated Research"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, use Crawl4AI to scrape this landing page and extract the core product features and pricing.",
    mcpReady: false,
    isFeatured: true,
    alternativeTo: ["Firecrawl", "Jina Reader", "ScrapingBee"],
  },
  {
    slug: "firecrawl",
    name: "Firecrawl",
    oneLiner: "Turn any website into LLM-ready Markdown or structured JSON.",
    description:
      "Firecrawl is an API-first service that crawls and scrapes websites, handling complex tasks like JavaScript rendering and bot detection automatically. It is designed to deliver perfectly formatted Markdown or JSON for AI agents and RAG systems. With 'Zero-Selector Extraction', you can use natural language to specify what data you want to extract, making it a favorite for AI-native operators building dynamic directories.",
    category: "Prospecting",
    logoUrl: "/logos/firecrawl.svg",
    websiteUrl: "https://www.firecrawl.dev",
    docsUrl: "https://docs.firecrawl.dev",
    pricingUrl: "https://www.firecrawl.dev/pricing",
    apiType: ["REST"],
    authMethod: ["Bearer Token"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/mendableai/firecrawl-mcp",
        label: "Official MCP Server",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Node.js", "Python", "Go", "Rust"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    aiCapabilities: ["Natural Language Extraction", "LLM-Ready Markdown", "Automatic Bot Bypass"],
    aiDifficulty: "AI-Native",
    starterPrompt: "Claude, crawl this documentation site with Firecrawl and extract all API endpoints into a JSON list.",
    mcpReady: true,
    isFeatured: true,
    alternativeTo: ["Crawl4AI", "Apify", "Jina Reader"],
  },
  {
    slug: "outscraper",
    name: "Outscraper",
    oneLiner: "Extract high-quality business data from Google Maps and beyond.",
    description:
      "Outscraper provides a powerful API for scraping business listings, reviews, and contact details from Google Maps, Amazon, and other public sources. It is widely used for building niche directories (as seen in the Frey Chu workflow) to gather initial seed data for local businesses or specialized industries. The API handles proxies and scaling, providing clean CSV or JSON outputs ready for AI enrichment.",
    category: "Prospecting",
    logoUrl: "/logos/outscraper.svg",
    websiteUrl: "https://outscraper.com",
    docsUrl: "https://app.outscraper.com/api-docs",
    pricingUrl: "https://outscraper.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js", "PHP"],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Bulk Business Scraping", "Google Maps Enrichment", "Review Analysis"],
    aiDifficulty: "Beginner-Friendly",
    starterPrompt: "Claude, use Outscraper to find the top 50 restaurants in Brooklyn with their website and phone number.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Apify", "Bright Data", "PhantomBuster"],
  },
  {
    slug: "hunter",
    name: "Hunter.io",
    oneLiner: "The standard for finding and verifying professional email addresses.",
    description:
      "Hunter.io provides a robust REST API for domain search, email finding, and email verification. It is a core tool for prospecting, allowing AI agents to find the right contacts at any company just by their domain. Hunter also offers an official MCP server, enabling AI assistants to perform real-time contact discovery and verification via chat.",
    category: "Prospecting",
    logoUrl: "/logos/hunter.svg",
    websiteUrl: "https://hunter.io",
    docsUrl: "https://hunter.io/api-documentation/v2",
    pricingUrl: "https://hunter.io/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/hunter-io/mcp-server",
        label: "Official MCP Server",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js", "Ruby", "PHP"],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Find Professional Emails", "Verify Email Deliverability", "Domain-based Prospecting"],
    aiDifficulty: "AI-Native",
    starterPrompt: "Claude, find the email pattern for stripe.com and find the email for their Head of Growth.",
    mcpReady: true,
    isFeatured: true,
    alternativeTo: ["Snov.io", "Prospeo", "Anymail Finder"],
  },
  {
    slug: "lusha",
    name: "Lusha",
    oneLiner: "Real-time B2B contact and company intelligence API.",
    description:
      "Lusha provides a RESTful API that delivers verified contact details and company firmographics. It is highly effective for enriching lead lists and providing AI agents with direct dials and personal emails for decision-makers. The Lusha API is built for speed and high-intent prospecting, ensuring that sales teams have the most accurate data at their fingertips.",
    category: "Prospecting",
    logoUrl: "/logos/lusha.svg",
    websiteUrl: "https://www.lusha.com",
    docsUrl: "https://www.lusha.com/api-documentation/",
    pricingUrl: "https://www.lusha.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    aiCapabilities: ["Direct Dial Enrichment", "Firmographic Data Retrieval", "Real-time Prospecting"],
    aiDifficulty: "Beginner-Friendly",
    starterPrompt: "Claude, enrich this list of LinkedIn URLs with Lusha to find their direct phone numbers.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Apollo.io", "ZoomInfo", "Kaspr"],
  },
  {
    slug: "exa-ai",
    name: "Exa.ai",
    oneLiner: "AI-native search engine for finding anything on the web.",
    description:
      "Exa (formerly Metaphor) is a search engine built from the ground up for LLMs. Its API allows AI agents to search the web using natural language and receive high-quality, structured results. Exa is exceptionally good at finding niche companies, blog posts, and research papers that traditional search engines miss. Its official MCP server makes it a primary tool for AI-led market research and prospecting.",
    category: "Prospecting",
    logoUrl: "/logos/exa.svg",
    websiteUrl: "https://exa.ai",
    docsUrl: "https://docs.exa.ai",
    pricingUrl: "https://exa.ai/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/exa-labs/exa-mcp-server",
        label: "Official MCP Server",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js"],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    aiCapabilities: ["Natural Language Search", "Company Research", "Find Niche Prospects"],
    aiDifficulty: "AI-Native",
    starterPrompt: "Claude, use Exa to find 20 startups in the 'AI Agents for Sales' space founded in the last 12 months.",
    mcpReady: true,
    isFeatured: true,
    alternativeTo: ["Perplexity", "Tavily", "Google Search API"],
  },
  {
    slug: "tavily",
    name: "Tavily AI",
    oneLiner: "Search engine optimized for AI agents and RAG applications.",
    description:
      "Tavily is a search engine designed specifically for AI agents to conduct real-time research with high accuracy. Its API provides clean, filtered results that are perfect for LLM context windows. With its official MCP server, AI assistants can seamlessly search the web and extract content from pages, making it an essential tool for automated market analysis and lead enrichment.",
    category: "Prospecting",
    logoUrl: "/logos/tavily.svg",
    websiteUrl: "https://tavily.com",
    docsUrl: "https://docs.tavily.com",
    pricingUrl: "https://tavily.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [
      {
        platform: "MCP",
        url: "https://docs.tavily.com/documentation/mcp",
        label: "Official MCP Server",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js"],
    hasWebhooks: false,
    hasOpenApiSpec: true,
    aiCapabilities: ["Real-time AI Search", "Web Data Extraction", "Automated Research via MCP"],
    aiDifficulty: "AI-Native",
    starterPrompt: "Claude, use Tavily to find the latest news about 'Salesforce Agentforce' from the last 7 days.",
    mcpReady: true,
    isFeatured: true,
    alternativeTo: ["Exa.ai", "Perplexity", "Google Search API"],
  },
  {
    slug: "perplexity",
    name: "Perplexity AI",
    oneLiner: "AI-powered research engine with a robust search and agent API.",
    description:
      "Perplexity provides an API that allows developers to integrate its powerful research and search capabilities into their own products. It offers the 'Sonar' models for real-time web search and an 'Agent API' for building advanced AI researchers. For AI-native operators, Perplexity's API is a primary choice for giving agents grounded, up-to-date information from across the web.",
    category: "Prospecting",
    logoUrl: "/logos/perplexity.svg",
    websiteUrl: "https://www.perplexity.ai",
    docsUrl: "https://docs.perplexity.ai",
    pricingUrl: "https://www.perplexity.ai/hub/api",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: ["Python", "Node.js"],
    hasWebhooks: false,
    hasOpenApiSpec: true,
    aiCapabilities: ["Grounded Web Research", "Real-time Search API", "Agentic Responses"],
    aiDifficulty: "Beginner-Friendly",
    starterPrompt: "Claude, use the Perplexity API to research the current competitive landscape for 'AI Video Prospecting'.",
    mcpReady: false,
    isFeatured: true,
    alternativeTo: ["OpenAI", "Tavily", "Exa.ai"],
  },
  {
    slug: "phantombuster",
    name: "PhantomBuster",
    oneLiner: "Automate lead generation and data extraction across any web platform.",
    description:
      "PhantomBuster's REST API allows developers to programmatically trigger 'Phantoms' (automated scripts) for scraping LinkedIn, Twitter, Google Maps, and more. It features 'Buster' functions for solving captchas and saving results. AI agents can use the API to launch specific automation workflows, fetch results, and manage leads in organizational storage without manual intervention.",
    category: "Prospecting",
    logoUrl: "/logos/phantombuster.svg",
    websiteUrl: "https://phantombuster.com",
    docsUrl: "https://hub.phantombuster.com/reference",
    pricingUrl: "https://phantombuster.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: ["Node.js"],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Launch Automated Phantoms", "Solve Captchas for Agents", "Fetch Scraped Lead Data"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, launch the 'LinkedIn Profile Scraper' Phantom in PhantomBuster using this list of profile URLs.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Apify", "Outscraper", "Bright Data"],
  },

  // ── Email Outreach ───────────────────────────────────────────
  {
    slug: "instantly",
    name: "Instantly.ai",
    oneLiner: "Cold email infrastructure and outreach automation at scale.",
    description:
      "Instantly.ai provides a REST API for managing cold email campaigns, warming up inboxes, and tracking deliverability metrics programmatically. Developers can create and schedule multi-step email sequences, manage unlimited sending accounts, and pull analytics on open rates, replies, and bounces. It is built for agencies and sales teams that need to scale outbound email without sacrificing deliverability.",
    category: "Email Outreach",
    logoUrl: "/logos/instantly.svg",
    websiteUrl: "https://instantly.ai",
    docsUrl: "https://developer.instantly.ai",
    pricingUrl: "https://instantly.ai/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Automate Cold Email", "Inbox Warmup", "Campaign Analytics"],
    aiDifficulty: "Beginner-Friendly",
    starterPrompt: "Claude, create a new cold email campaign in Instantly for the lead list I just generated.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Lemlist", "Smartlead", "Woodpecker"],
  },
  {
    slug: "resend",
    name: "Resend",
    oneLiner: "Modern email API built for developers.",
    description:
      "Resend is a developer-first email API that makes sending transactional and marketing emails simple and reliable. The REST API supports sending emails with React components as templates, domain verification, audience management, and detailed delivery analytics. With SDKs for Python, Node.js, Go, and Ruby, Resend is ideal for SaaS teams that want to own their email infrastructure with minimal setup.",
    category: "Email Outreach",
    logoUrl: "/logos/resend.svg",
    websiteUrl: "https://resend.com",
    docsUrl: "https://resend.com/docs",
    pricingUrl: "https://resend.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/resend/mcp-server",
        label: "Official MCP Server",
        mcpConfig: '{\n  "mcpServers": {\n    "resend": {\n      "command": "npx",\n      "args": ["-y", "@resend/mcp-server"],\n      "env": {\n        "RESEND_API_KEY": "YOUR_API_KEY"\n      }\n    }\n  }\n}',
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js", "Go", "Ruby"],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Send Transactional Email", "Manage Audiences", "React Templates"],
    aiDifficulty: "AI-Native",
    starterPrompt: "Claude, send a welcome email via Resend to user@example.com using the 'Welcome' template.",
    mcpReady: true,
    isFeatured: false,
    alternativeTo: ["SendGrid", "Postmark", "Mailgun"],
  },
  {
    slug: "loops",
    name: "Loops",
    oneLiner: "Email platform for modern SaaS companies.",
    description:
      "Loops provides a REST API for sending transactional emails, managing contacts, and triggering event-based email campaigns. It is designed specifically for SaaS companies that need to combine marketing loops, onboarding sequences, and product emails in one platform. The API is clean and well-documented, making it easy to integrate lifecycle email into your application.",
    category: "Email Outreach",
    logoUrl: "/logos/loops.svg",
    websiteUrl: "https://loops.so",
    docsUrl: "https://loops.so/docs/api",
    pricingUrl: "https://loops.so/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: ["Node.js"],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["SaaS Lifecycle Email", "Trigger Events", "Contact Management"],
    aiDifficulty: "Beginner-Friendly",
    starterPrompt: "Claude, trigger the 'Post-Purchase' event in Loops for customer 'akhil@example.com'.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Customer.io", "Mailchimp", "Resend"],
  },
  {
    slug: "lemlist",
    name: "lemlist",
    oneLiner: "Sales engagement platform with advanced personalization and outreach APIs.",
    description:
      "lemlist offers a developer API designed for automating multichannel outreach, building custom workflows, and enriching databases. It features 'lemlist AI' which helps with lead segmentation and personalized content generation. The API allows you to manage campaigns, trigger actions based on prospect behavior, and sync data seamlessly with your CRM, making it a powerful tool for AI-driven sales teams.",
    category: "Email Outreach",
    logoUrl: "/logos/lemlist.svg",
    websiteUrl: "https://www.lemlist.com",
    docsUrl: "https://developer.lemlist.com",
    pricingUrl: "https://www.lemlist.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Personalized Multichannel Outreach", "Lead Segmentation", "Campaign Automation"],
    aiDifficulty: "Beginner-Friendly",
    starterPrompt: "Claude, create a new lemlist campaign and add these 50 leads with personalized icebreakers.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Instantly.ai", "Salesloft", "Outreach"],
  },
  {
    slug: "smartlead",
    name: "Smartlead.ai",
    oneLiner: "Scale your outbound with AI-powered cold email automation.",
    description:
      "Smartlead provides a powerful REST API for automating cold email campaigns, managing master inboxes, and tracking lead statistics. It features 'Smart Prospect' for lead search and 'Smart Delivery' for deliverability optimization. The API allows AI agents to push leads to campaigns, manage sequences, and respond to replies directly from a centralized master inbox.",
    category: "Email Outreach",
    logoUrl: "/logos/smartlead.svg",
    websiteUrl: "https://www.smartlead.ai",
    docsUrl: "https://api.smartlead.ai/reference",
    pricingUrl: "https://www.smartlead.ai/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Automated Lead Pushing", "Master Inbox Management", "Campaign Sequence Control"],
    aiDifficulty: "Beginner-Friendly",
    starterPrompt: "Claude, push these 100 leads to the 'Product Launch' campaign in Smartlead and set their category to 'Interested'.",
    mcpReady: false,
    isFeatured: true,
    alternativeTo: ["Instantly.ai", "Lemlist", "Outreach"],
  },

  // ── CRM ──────────────────────────────────────────────────────
  {
    slug: "attio",
    name: "Attio",
    oneLiner: "Next-generation CRM with a powerful, flexible API.",
    description:
      "Attio is a modern CRM that exposes a comprehensive REST API for managing contacts, companies, deals, and custom objects. The API supports complex filtering, real-time webhooks, and full CRUD on all data models. Attio also offers an official MCP server, making it one of the first CRMs to support the Model Context Protocol for AI-powered integrations.",
    category: "CRM",
    logoUrl: "/logos/attio.svg",
    websiteUrl: "https://attio.com",
    docsUrl: "https://developers.attio.com",
    pricingUrl: "https://attio.com/pricing",
    apiType: ["REST"],
    authMethod: ["OAuth2", "Bearer Token"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/attio/mcp-server",
        label: "Official MCP Server",
        mcpConfig: '{\n  "mcpServers": {\n    "attio": {\n      "command": "npx",\n      "args": ["-y", "@attio/mcp-server"],\n      "env": {\n        "ATTIO_ACCESS_TOKEN": "YOUR_ACCESS_TOKEN"\n      }\n    }\n  }\n}',
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Node.js"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://developers.attio.com/reference/openapi-spec",
    aiCapabilities: ["Custom CRM Objects", "Real-time Webhooks", "Relationship Mapping"],
    aiDifficulty: "AI-Native",
    starterPrompt: "Claude, find all Attio records in the 'Seed Funding' stage and summarize their latest interactions.",
    mcpReady: true,
    isFeatured: false,
    alternativeTo: ["HubSpot", "Salesforce", "Folk"],
  },
  {
    slug: "twenty",
    name: "Twenty",
    oneLiner: "Open-source CRM with REST and GraphQL APIs.",
    description:
      "Twenty is an open-source CRM that offers both REST and GraphQL APIs for full control over your customer data. Self-host it or use the cloud version to manage contacts, companies, opportunities, and custom objects. The GraphQL API provides flexible querying, while the REST API covers standard CRUD operations. As an open-source project, Twenty gives teams complete transparency and the ability to extend the platform.",
    category: "CRM",
    logoUrl: "/logos/twenty.svg",
    websiteUrl: "https://twenty.com",
    docsUrl: "https://twenty.com/developers",
    pricingUrl: "https://twenty.com/pricing",
    githubUrl: "https://github.com/twentyhq/twenty",
    apiType: ["REST", "GraphQL"],
    authMethod: ["API Key", "Bearer Token"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://twenty.com/developers/rest-api",
    aiCapabilities: ["Open-source CRM", "GraphQL & REST", "Self-hosting"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, write a GraphQL query for Twenty to fetch all opportunities closing this month.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Salesforce", "HubSpot", "Attio"],
  },
  {
    slug: "hubspot",
    name: "HubSpot",
    oneLiner: "All-in-one CRM platform with an extensive API ecosystem.",
    description:
      "HubSpot offers one of the most comprehensive CRM APIs in the market, covering contacts, companies, deals, tickets, marketing, and custom objects. The REST API supports batch operations, advanced filtering with CRM search, and real-time webhooks. With official SDKs in Python, Node.js, Ruby, and PHP, plus an MCP server for AI integrations, HubSpot is the industry standard for CRM automation and is trusted by over 200,000 businesses worldwide.",
    category: "CRM",
    logoUrl: "/logos/hubspot.svg",
    websiteUrl: "https://www.hubspot.com",
    docsUrl: "https://developers.hubspot.com",
    pricingUrl: "https://www.hubspot.com/pricing",
    apiType: ["REST"],
    authMethod: ["OAuth2", "Bearer Token", "API Key"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/hubspot/hubspot-mcp",
        label: "Official MCP Server",
        mcpConfig: '{\n  "mcpServers": {\n    "hubspot": {\n      "command": "npx",\n      "args": ["-y", "@hubspot/mcp-server"],\n      "env": {\n        "HUBSPOT_ACCESS_TOKEN": "YOUR_ACCESS_TOKEN"\n      }\n    }\n  }\n}',
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js", "Ruby", "PHP"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://api.hubspot.com/api-catalog-public/v1/apis",
    aiCapabilities: ["Update Deals", "Search CRM", "Marketing Sync"],
    aiDifficulty: "AI-Native",
    starterPrompt: "Claude, find all HubSpot deals over $50k that are in the 'Discovery' stage.",
    mcpReady: true,
    isFeatured: true,
    alternativeTo: ["Salesforce", "Attio", "Pipedrive"],
  },
  {
    slug: "salesforce",
    name: "Salesforce",
    oneLiner: "The world's leading enterprise CRM with comprehensive API and AI tools.",
    description:
      "Salesforce provides a massive ecosystem of APIs (REST, SOAP, Bulk) for managing every aspect of the customer journey. It has recently introduced Salesforce Hosted MCP Servers, allowing teams to expose Salesforce data as tools for AI agents. With Einstein AI and Agentforce, Salesforce is pushing the boundaries of autonomous sales operations, making it a critical hub for AI-native enterprise workflows.",
    category: "CRM",
    logoUrl: "/logos/salesforce.svg",
    websiteUrl: "https://www.salesforce.com",
    docsUrl: "https://developer.salesforce.com/docs",
    pricingUrl: "https://www.salesforce.com/pricing",
    apiType: ["REST"],
    authMethod: ["OAuth2"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/salesforce/mcp-server",
        label: "Salesforce MCP (Beta)",
      },
    ],
    hasFreeTier: false,
    sdkLanguages: ["Java", "Node.js", "Python"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    aiCapabilities: ["Agentforce Autonomous Actions", "Predictive Scoring", "Custom AI Tools via MCP"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, list the top 10 open opportunities in Salesforce and summarize the last 3 activities for each.",
    mcpReady: true,
    isFeatured: false,
    alternativeTo: ["HubSpot", "Microsoft Dynamics 365", "Zoho CRM"],
  },
  {
    slug: "zoho-crm",
    name: "Zoho CRM",
    oneLiner: "Flexible CRM for growing businesses with native AI and MCP support.",
    description:
      "Zoho CRM provides a powerful REST API and a specialized 'Zoho MCP' service that allows developers to create custom MCP servers for AI agents. This enables AI assistants to perform complex actions across the Zoho suite. With Zia (Zoho's AI assistant) providing sales predictions and anomaly detection, Zoho is a top choice for teams building automated, AI-augmented sales processes.",
    category: "CRM",
    logoUrl: "/logos/zoho.svg",
    websiteUrl: "https://www.zoho.com/crm",
    docsUrl: "https://www.zoho.com/crm/developer/docs/api/v6/",
    pricingUrl: "https://www.zoho.com/crm/pricing.html",
    apiType: ["REST"],
    authMethod: ["OAuth2"],
    integrations: [
      {
        platform: "MCP",
        url: "https://www.zoho.com/mcp/",
        label: "Official Zoho MCP",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Java", "Node.js", "Python", "PHP", "C#"],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Zoho MCP Orchestration", "Zia Sales Predictions", "Anomaly Detection"],
    aiDifficulty: "Beginner-Friendly",
    starterPrompt: "Claude, use Zoho MCP to fetch the contact details for 'Acme Corp' and create a new task for tomorrow.",
    mcpReady: true,
    isFeatured: false,
    alternativeTo: ["HubSpot", "Salesforce", "Pipedrive"],
  },
  {
    slug: "pipedrive",
    name: "Pipedrive",
    oneLiner: "Sales-focused CRM with a robust REST API for deal management.",
    description:
      "Pipedrive offers a developer-friendly REST API designed to help sales teams manage their pipelines programmatically. It features high performance and a clean data structure, making it ideal for AI agents to track deals, manage activities, and update contact information. Pipedrive also has an official MCP server, facilitating natural language interaction with CRM data.",
    category: "CRM",
    logoUrl: "/logos/pipedrive.svg",
    websiteUrl: "https://www.pipedrive.com",
    docsUrl: "https://developers.pipedrive.com/docs/api/v1/",
    pricingUrl: "https://www.pipedrive.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key", "OAuth2"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/pipedrive/mcp-server",
        label: "Official MCP Server",
      },
    ],
    hasFreeTier: false,
    sdkLanguages: ["Node.js", "PHP", "Python"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    aiCapabilities: ["Pipeline Management", "Activity Tracking", "AI CRM Automation"],
    aiDifficulty: "Beginner-Friendly",
    starterPrompt: "Claude, move the 'Acme Corp' deal to the 'Contract Sent' stage in Pipedrive.",
    mcpReady: true,
    isFeatured: false,
    alternativeTo: ["HubSpot", "Salesforce", "Zoho CRM"],
  },
  {
    slug: "folk",
    name: "Folk",
    oneLiner: "Lightweight CRM designed for relationship-driven teams.",
    description:
      "Folk is a collaborative CRM with a REST API that lets you manage contacts, companies, and pipelines programmatically. The API supports creating and updating records, managing custom fields, and syncing data from external sources. Folk is built for teams that prioritize relationships over rigid sales processes, making it popular with VCs, agencies, and partnership teams.",
    category: "CRM",
    logoUrl: "/logos/folk.svg",
    websiteUrl: "https://www.folk.app",
    docsUrl: "https://developers.folk.app",
    pricingUrl: "https://www.folk.app/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Attio", "HubSpot", "Streak"],
  },
  {
    slug: "arpedio",
    name: "ARPEDIO",
    oneLiner: "Account-based selling platform for Salesforce.",
    description: "ARPEDIO is a Salesforce-native application that provides a suite of tools for account-based selling, including account planning, opportunity management, org charts, and relationship mapping. It helps sales teams to better understand their customers and to identify and close more deals.",
    category: "CRM",
    logoUrl: "/logos/arpedio.svg",
    websiteUrl: "http://www.arpedio.com",
    docsUrl: "https://arpedio.com/arpedio-consulting/",
    pricingUrl: "https://arpedio.com/#bookdemo",
    apiType: ["REST"],
    authMethod: ["OAuth2"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: ["Apex"],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Account Planning", "Opportunity Management", "Relationship Mapping", "Org Charts"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, show me the org chart for the Acme Corporation account in ARPEDIO.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Salesforce Maps", "Groove", "Lucidchart"],
  },

  // ── Enrichment ───────────────────────────────────────────────
  {
    slug: "clearbit",
    name: "Clearbit (Breeze)",
    oneLiner: "Real-time company and person enrichment API by HubSpot.",
    description:
      "Clearbit, now part of HubSpot as Breeze Intelligence, provides REST APIs for enriching person and company records in real time. Look up any email or domain to get firmographic data, technographics, employee counts, funding details, and more. The Enrichment API powers lead scoring, routing, and personalization for thousands of B2B companies and integrates natively with HubSpot CRM.",
    category: "Enrichment",
    logoUrl: "/logos/clearbit.svg",
    websiteUrl: "https://clearbit.com",
    docsUrl: "https://dashboard.clearbit.com/docs",
    pricingUrl: "https://clearbit.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key", "Bearer Token"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: ["Node.js", "Python"],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["People Data Labs", "ZoomInfo", "Apollo.io"],
  },
  {
    slug: "people-data-labs",
    name: "People Data Labs",
    oneLiner: "B2B data API with 3 billion person and company records.",
    description:
      "People Data Labs provides a REST API for accessing one of the largest people and company datasets available. Use the Person Enrichment, Company Enrichment, and Search APIs to build prospecting lists, enrich CRM records, and power data-driven applications. With SDKs in Python, Node.js, Go, and Ruby, PDL is designed for developers building data products and go-to-market tools at scale.",
    category: "Enrichment",
    logoUrl: "/logos/people-data-labs.svg",
    websiteUrl: "https://www.peopledatalabs.com",
    docsUrl: "https://docs.peopledatalabs.com",
    pricingUrl: "https://www.peopledatalabs.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js", "Go", "Ruby"],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Clearbit", "ZoomInfo", "Apollo.io"],
  },
  {
    slug: "proxycurl",
    name: "Proxycurl",
    oneLiner: "API for scraping and enriching LinkedIn profile data.",
    description:
      "Proxycurl provides a REST API that extracts structured data from LinkedIn profiles and company pages without requiring a LinkedIn account or dealing with rate limits. Use it to enrich leads with job titles, work history, education, skills, and company details. Proxycurl is popular among sales and recruiting teams that need reliable LinkedIn data for prospecting and research workflows.",
    category: "Enrichment",
    logoUrl: "/logos/proxycurl.svg",
    websiteUrl: "https://nubela.co/proxycurl",
    docsUrl: "https://nubela.co/proxycurl/docs",
    pricingUrl: "https://nubela.co/proxycurl/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: ["Python"],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Clearbit", "People Data Labs", "PhantomBuster"],
  },
  {
    slug: "jina-reader",
    name: "Jina Reader",
    oneLiner: "Convert any URL to LLM-friendly Markdown for AI processing.",
    description:
      "Jina Reader is an API that extracts the core content from any webpage and converts it into clean Markdown. It is a critical 'Lego block' for AI-native operators who need to give their agents the ability to 'read' the web. Its official MCP server allows AI assistants to fetch and process web content in real-time for research, summarization, and data extraction.",
    category: "Enrichment",
    logoUrl: "/logos/jina.svg",
    websiteUrl: "https://jina.ai/reader",
    docsUrl: "https://jina.ai/reader/api",
    pricingUrl: "https://jina.ai/reader/pricing",
    apiType: ["REST"],
    authMethod: ["API Key", "None"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/jina-ai/mcp-server",
        label: "Official MCP Server",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js"],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    aiCapabilities: ["URL to Markdown Conversion", "Web Content Extraction", "RAG Data Pipeline"],
    aiDifficulty: "AI-Native",
    starterPrompt: "Claude, use Jina Reader to fetch the content of this technical blog post and summarize the key findings.",
    mcpReady: true,
    isFeatured: true,
    alternativeTo: ["Firecrawl", "Crawl4AI", "Reader API"],
  },
  {
    slug: "voyage-ai",
    name: "Voyage AI",
    oneLiner: "State-of-the-art embedding and reranking models for RAG.",
    description:
      "Voyage AI provides specialized embedding and reranking API models that are optimized for retrieval accuracy. For AI-native operators, Voyage is a critical component for building custom 'brain' systems that can find exactly the right sales context from massive document sets or CRM histories. Their models are known for outperforming general-purpose embeddings in sales and technical domains.",
    category: "Enrichment",
    logoUrl: "/logos/voyage.svg",
    websiteUrl: "https://www.voyageai.com",
    docsUrl: "https://docs.voyageai.com",
    pricingUrl: "https://www.voyageai.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js"],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    aiCapabilities: ["Specialized Text Embeddings", "Document Reranking", "AI Search Optimization"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, use Voyage AI to rerank these 100 search results to find the most relevant case study for this customer.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["OpenAI Embeddings", "Cohere", "Pinecone"],
  },

  // ── Voice & Calling ──────────────────────────────────────────
  {
    slug: "bland-ai",
    name: "Bland.ai",
    oneLiner: "AI phone calling API for sales and support automation.",
    description:
      "Bland.ai provides a REST API for making and receiving AI-powered phone calls at scale. Build automated outbound calling campaigns, inbound call handling, and conversational voice agents without managing telephony infrastructure. The API supports custom voice personas, call transfers, and real-time transcription, making it ideal for sales teams looking to automate qualification calls and appointment setting.",
    category: "Voice & Calling",
    logoUrl: "/logos/bland-ai.svg",
    websiteUrl: "https://www.bland.ai",
    docsUrl: "https://docs.bland.ai",
    pricingUrl: "https://www.bland.ai/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Vapi", "Retell.ai", "Air.ai"],
  },
  {
    slug: "vapi",
    name: "Vapi",
    oneLiner: "Developer platform for building voice AI agents.",
    description:
      "Vapi is a developer-first platform with a REST API for building, testing, and deploying voice AI agents. Create custom voice assistants that can make and receive phone calls, handle complex conversations, and integrate with your existing tools. Vapi supports multiple LLM providers, custom voices, function calling, and real-time streaming, giving developers full control over the voice AI experience.",
    category: "Voice & Calling",
    logoUrl: "/logos/vapi.svg",
    websiteUrl: "https://vapi.ai",
    docsUrl: "https://docs.vapi.ai",
    pricingUrl: "https://vapi.ai/pricing",
    apiType: ["REST"],
    authMethod: ["Bearer Token"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://docs.vapi.ai/api-reference/openapi-spec",
    isFeatured: true,
    alternativeTo: ["Bland.ai", "Retell.ai", "Twilio"],
  },
  {
    slug: "retell-ai",
    name: "Retell AI",
    oneLiner: "The platform for building high-performance conversational AI voice agents.",
    description:
      "Retell AI provides a comprehensive REST API and SDK for creating, managing, and deploying AI voice agents that can make and receive phone calls. It features a 'Retell LLM Response Engine' and supports complex conversation flows. For AI-native operators, it offers an 'MCP Tool' capability, making it exceptionally easy to integrate voice interactions into agentic workflows.",
    category: "Voice & Calling",
    logoUrl: "/logos/retell.svg",
    websiteUrl: "https://www.retellai.com",
    docsUrl: "https://docs.retellai.com",
    pricingUrl: "https://www.retellai.com/pricing",
    apiType: ["REST", "WebSocket"],
    authMethod: ["Bearer Token"],
    integrations: [
      {
        platform: "MCP",
        url: "https://docs.retellai.com/api-references/get-mcp-tools",
        label: "Retell MCP Tools",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Node.js", "Python"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    aiCapabilities: ["Real-time Voice Conversation", "Automated Outbound Calling", "Voice Agent Management via MCP"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, create a new Retell AI voice agent with a 'Professional Sales' persona and link it to my phone number.",
    mcpReady: true,
    isFeatured: true,
    alternativeTo: ["Vapi", "Bland.ai", "Air.ai"],
  },
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    oneLiner: "Advanced AI audio platform for realistic text-to-speech and voice agents.",
    description:
      "ElevenLabs offers a developer API for generating high-quality AI voices, dubbing, and text-to-speech. Its new 'ElevenAgents' platform allows developers to build conversational voice assistants with low latency. For AI-native operators, ElevenLabs is the gold standard for creating personalized voice outreach and automating customer calls with human-like sound.",
    category: "Voice & Calling",
    logoUrl: "/logos/elevenlabs.svg",
    websiteUrl: "https://elevenlabs.io",
    docsUrl: "https://elevenlabs.io/docs",
    pricingUrl: "https://elevenlabs.io/pricing",
    apiType: ["REST", "WebSocket"],
    authMethod: ["API Key"],
    integrations: [
      {
        platform: "MCP",
        url: "https://elevenlabs.io/docs/eleven-agents/mcp",
        label: "ElevenLabs MCP",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    aiCapabilities: ["Human-like Voice Synthesis", "Voice-to-Voice Agents", "Automated Dubbing"],
    aiDifficulty: "Beginner-Friendly",
    starterPrompt: "Claude, use ElevenLabs to generate a personalized audio message for this prospect using the 'Marcus' voice.",
    mcpReady: true,
    isFeatured: true,
    alternativeTo: ["OpenAI Voice", "Play.ht", "Murf.ai"],
  },

  // ── Scheduling ───────────────────────────────────────────────
  {
    slug: "cal-com",
    name: "Cal.com",
    oneLiner: "Open-source scheduling infrastructure with a full API.",
    description:
      "Cal.com is the open-source alternative to Calendly, offering a REST API for managing event types, bookings, availability, and users programmatically. Embed scheduling into your product, sync calendars, and automate booking workflows. As an open-source project, Cal.com gives you full control over your scheduling infrastructure, with options to self-host or use the managed cloud platform.",
    category: "Scheduling",
    logoUrl: "/logos/cal-com.svg",
    websiteUrl: "https://cal.com",
    docsUrl: "https://cal.com/docs/api-reference",
    pricingUrl: "https://cal.com/pricing",
    githubUrl: "https://github.com/calcom/cal.com",
    apiType: ["REST"],
    authMethod: ["API Key", "OAuth2"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://api.cal.com/v2/docs",
    isFeatured: true,
    alternativeTo: ["Calendly", "SavvyCal", "TidyCal"],
  },
  {
    slug: "calendly",
    name: "Calendly",
    oneLiner: "Scheduling automation platform with a robust API.",
    description:
      "Calendly's REST API allows developers to manage event types, list scheduled events, handle invitee data, and subscribe to real-time webhooks for booking notifications. Integrate Calendly into your sales workflow to automate meeting scheduling, route leads to the right reps, and sync booking data with your CRM. Calendly is the most widely adopted scheduling tool for sales and customer-facing teams.",
    category: "Scheduling",
    logoUrl: "/logos/calendly.svg",
    websiteUrl: "https://calendly.com",
    docsUrl: "https://developer.calendly.com",
    pricingUrl: "https://calendly.com/pricing",
    apiType: ["REST"],
    authMethod: ["OAuth2", "Bearer Token"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Cal.com", "SavvyCal", "Chili Piper"],
  },
  {
    slug: "chili-piper",
    name: "Chili Piper",
    oneLiner: "Advanced scheduling and routing API for revenue teams.",
    description:
      "Chili Piper provides a powerful API for automating complex booking and routing workflows. It is designed for high-growth sales teams that need to route leads to the right account executive instantly. The API allows for programmatic calendar management and queue-based routing, ensuring that every high-intent lead is scheduled without friction.",
    category: "Scheduling",
    logoUrl: "/logos/chili-piper.svg",
    websiteUrl: "https://www.chilipiper.com",
    docsUrl: "https://help.chilipiper.com/hc/en-us/articles/360046247933-Chili-Piper-API",
    pricingUrl: "https://www.chilipiper.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Automated Lead Routing", "Calendar Queue Management", "Instant Booking Workflows"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, use Chili Piper to book a meeting for this qualified lead in the 'SDR' queue.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Calendly", "Cal.com", "SavvyCal"],
  },

  // ── Conversation Intelligence ────────────────────────────────
  {
    slug: "fireflies",
    name: "Fireflies.ai",
    oneLiner: "AI meeting assistant with transcription and analytics APIs.",
    description:
      "Fireflies.ai offers both REST and GraphQL APIs for accessing meeting transcripts, summaries, action items, and conversation analytics. Automatically record and transcribe meetings from Zoom, Google Meet, and Teams, then query the data programmatically. The GraphQL API is especially powerful for building custom dashboards and integrating meeting intelligence into your sales stack.",
    category: "Conversation Intelligence",
    logoUrl: "/logos/fireflies.svg",
    websiteUrl: "https://fireflies.ai",
    docsUrl: "https://docs.fireflies.ai",
    pricingUrl: "https://fireflies.ai/pricing",
    apiType: ["REST", "GraphQL"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Gong", "Chorus", "Otter.ai"],
  },
  {
    slug: "recall-ai",
    name: "Recall.ai",
    oneLiner: "Universal meeting bot API for real-time audio and video.",
    description:
      "Recall.ai provides a REST API that lets you deploy meeting bots to Zoom, Google Meet, Microsoft Teams, and other platforms to capture real-time audio, video, and transcription data. Build conversation intelligence, coaching tools, or compliance recording features without managing complex WebRTC or bot infrastructure. Recall.ai handles the heavy lifting of joining meetings and streaming media reliably.",
    category: "Conversation Intelligence",
    logoUrl: "/logos/recall-ai.svg",
    websiteUrl: "https://www.recall.ai",
    docsUrl: "https://docs.recall.ai",
    pricingUrl: "https://www.recall.ai/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://docs.recall.ai/reference",
    isFeatured: false,
    alternativeTo: ["Fireflies.ai", "Gong", "Assembly AI"],
  },
  {
    slug: "gong",
    name: "Gong",
    oneLiner: "The industry standard for revenue intelligence and conversation analysis.",
    description:
      "Gong's REST API gives teams programmatic access to the world's most advanced conversation intelligence platform. It allows AI agents to extract insights from sales calls, analyze deal sentiment, and identify coaching opportunities. Gong is a critical hub for high-performing sales teams that want to use AI to understand what's actually happening in their customer conversations.",
    category: "Conversation Intelligence",
    logoUrl: "/logos/gong.svg",
    websiteUrl: "https://www.gong.io",
    docsUrl: "https://help.gong.io/docs",
    pricingUrl: "https://www.gong.io/pricing",
    apiType: ["REST"],
    authMethod: ["Basic Auth"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Conversation Analysis", "Deal Sentiment Tracking", "Meeting Insight Extraction"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, summarize the common objections mentioned in the last 10 calls for the 'Stripe' deal in Gong.",
    mcpReady: false,
    isFeatured: true,
    alternativeTo: ["Chorus.ai", "Fireflies.ai", "Otter.ai"],
  },

  // ── Documents & Proposals ────────────────────────────────────
  {
    slug: "pandadoc",
    name: "PandaDoc",
    oneLiner: "API for document generation, e-signatures, and tracking.",
    description:
      "PandaDoc provides a powerful REST API for automating the creation, sending, and signing of sales documents. It allows AI agents to generate custom proposals and contracts based on CRM data, track real-time engagement, and trigger workflows upon signature. Its official MCP server enables AI assistants to manage the entire document lifecycle directly from chat.",
    category: "Documents & Proposals",
    logoUrl: "/logos/pandadoc.svg",
    websiteUrl: "https://www.pandadoc.com",
    docsUrl: "https://developers.pandadoc.com",
    pricingUrl: "https://www.pandadoc.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key", "OAuth2"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/pandadoc/mcp-server",
        label: "Official MCP Server",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Node.js", "Python", "Java", "PHP"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    aiCapabilities: ["Automated Document Generation", "E-signature Orchestration", "Document Status Tracking"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, generate a proposal in PandaDoc for 'Acme Corp' using the 'Standard Sales' template.",
    mcpReady: true,
    isFeatured: true,
    alternativeTo: ["DocuSign", "HelloSign", "Proposify"],
  },

  // ── Sales Engagement ─────────────────────────────────────────
  {
    slug: "salesloft",
    name: "Salesloft",
    oneLiner: "API for orchestrating multi-channel sales engagement.",
    description:
      "Salesloft's REST API allows developers to build custom workflows for multi-channel outreach across email, phone, and social. It is a core tool for sales engagement, enabling AI agents to manage cadences, track engagement metrics, and prioritize tasks for sales reps. The API is robust and well-documented, making it a primary choice for enterprise-level sales automation.",
    category: "Sales Engagement",
    logoUrl: "/logos/salesloft.svg",
    websiteUrl: "https://salesloft.com",
    docsUrl: "https://developer.salesloft.com",
    pricingUrl: "https://salesloft.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key", "OAuth2"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    aiCapabilities: ["Cadence Management", "Outreach Orchestration", "Engagement Analytics"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, list all prospects in Salesloft who haven't been contacted in the last 7 days.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Outreach", "lemlist", "Groove"],
  },
  {
    slug: "outreach",
    name: "Outreach",
    oneLiner: "The sales execution platform with comprehensive execution APIs.",
    description:
      "Outreach provides a massive REST API for managing every touchpoint of the sales execution process. It allows AI agents to manage prospects, sequences, and tasks at scale. With its focus on 'Sales Execution Intelligence', Outreach is a critical hub for teams that want to use AI to drive better sales outcomes through disciplined outreach and engagement.",
    category: "Sales Engagement",
    logoUrl: "/logos/outreach.svg",
    websiteUrl: "https://www.outreach.io",
    docsUrl: "https://developers.outreach.io/api/reference/",
    pricingUrl: "https://www.outreach.io/pricing",
    apiType: ["REST"],
    authMethod: ["OAuth2"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    aiCapabilities: ["Sequence Automation", "Prospect Lifecycle Management", "Sales Execution Insights"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, add these 5 new leads to the 'Initial Outreach' sequence in Outreach.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Salesloft", "lemlist", "Apollo.io"],
  },
  {
    slug: "showpad",
    name: "Showpad",
    oneLiner: "The Enablement Operating System® for modern sales teams.",
    description: "Showpad is a sales enablement platform that helps sales and marketing teams to create better buyer experiences. It provides a single platform for sales content management, training, and coaching, and offers an open API for building custom integrations and workflows.",
    category: "Sales Engagement",
    logoUrl: "/logos/showpad.svg",
    websiteUrl: "https://www.showpad.com",
    docsUrl: "https://developer.showpad.com/",
    pricingUrl: "https://www.showpad.com/product/pricing",
    apiType: ["REST"],
    authMethod: ["OAuth2"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://developer.showpad.com/api/v4/swagger.yaml",
    aiCapabilities: ["Content Management", "Sales Coaching", "Buyer Engagement"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, find the latest presentation about our new product in Showpad.",
    mcpReady: false,
    isFeatured: false,
    alternativeTo: ["Salesloft", "Outreach", "Highspot"],
  },

  // ── Workflow Automation ──────────────────────────────────────
  {
    slug: "n8n",
    name: "n8n",
    oneLiner: "Open-source workflow automation with a powerful API.",
    description:
      "n8n is an open-source workflow automation platform with a REST API for managing workflows, executions, and credentials programmatically. Build complex sales automations by connecting 400+ integrations, trigger workflows via webhooks, and monitor execution history through the API. Self-host n8n for full control or use the cloud version for managed infrastructure.",
    category: "Workflow Automation",
    logoUrl: "/logos/n8n.svg",
    websiteUrl: "https://n8n.io",
    docsUrl: "https://docs.n8n.io/api/",
    pricingUrl: "https://n8n.io/pricing",
    githubUrl: "https://github.com/n8n-io/n8n",
    apiType: ["REST"],
    authMethod: ["API Key", "Basic Auth"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://docs.n8n.io/api/api-reference/",
    isFeatured: false,
    alternativeTo: ["Zapier", "Make", "Tray.io"],
  },
  {
    slug: "apideck",
    name: "Apideck",
    oneLiner: "Unified API platform for building real-time AI integrations.",
    description:
      "Apideck provides unified APIs that normalize data models across 150+ software providers. For AI-native operators, Apideck is a game-changer as it acts as an orchestration layer, allowing AI agents to interact with multiple CRMs, HRIS, and accounting tools using a single, standardized schema. Their focus on LLM-ready data makes it ideal for building complex, cross-platform AI agents.",
    category: "Workflow Automation",
    logoUrl: "/logos/apideck.svg",
    websiteUrl: "https://www.apideck.com",
    docsUrl: "https://developers.apideck.com",
    pricingUrl: "https://www.apideck.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key", "Bearer Token"],
    integrations: [
      {
        platform: "Custom",
        url: "https://www.apideck.com/ecosystem",
        label: "Unified API Ecosystem",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Node.js", "Python", "Go"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    aiCapabilities: ["Unified CRM Actions", "LLM-Ready Data Models", "AI Orchestration Layer"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, use Apideck to fetch contact data from the customer's connected CRM, regardless of whether they use HubSpot or Salesforce.",
    mcpReady: false,
    isFeatured: true,
    alternativeTo: ["Merge.dev", "Nango", "Finch"],
  },
  {
    slug: "nango",
    name: "Nango",
    oneLiner: "Open-source product integration platform for AI agents.",
    description:
      "Nango is a code-first integration platform that gives developers instant access to 600+ APIs. It provides managed authentication, API action introspection, and action triggering specifically designed for AI agents. Nango's support for the Model Context Protocol (MCP) and its ability to handle complex auth flows make it a primary choice for builders equipping their AI assistants with 'hands' to take actions across the web.",
    category: "Workflow Automation",
    logoUrl: "/logos/nango.svg",
    websiteUrl: "https://www.nango.dev",
    docsUrl: "https://docs.nango.dev",
    pricingUrl: "https://www.nango.dev/pricing",
    githubUrl: "https://github.com/nangohq/nango",
    apiType: ["REST"],
    authMethod: ["API Key", "OAuth2"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/nangohq/nango-mcp",
        label: "Official MCP Support",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Node.js", "Python"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    aiCapabilities: ["Managed Auth for Agents", "600+ API Integrations", "MCP Orchestration"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, use Nango to authenticate with the user's Outreach account and list all active sequences.",
    mcpReady: true,
    isFeatured: false,
    alternativeTo: ["Apideck", "Merge.dev", "Zapier"],
  },
  {
    slug: "zapier",
    name: "Zapier",
    oneLiner: "The world's largest automation ecosystem with an MCP server.",
    description:
      "Zapier allows you to connect over 7,000+ apps and automate workflows without code. Its official MCP server is a massive leap for AI-native operators, as it gives AI agents 'hands' to perform over 30,000+ actions across any connected app. Whether it's adding a row to a spreadsheet or sending a Slack message, Zapier via MCP is the ultimate universal connector for AI assistants.",
    category: "Workflow Automation",
    logoUrl: "/logos/zapier.svg",
    websiteUrl: "https://zapier.com",
    docsUrl: "https://zapier.com/engineering/mcp",
    pricingUrl: "https://zapier.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key", "OAuth2"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/zapier/mcp-server",
        label: "Official MCP Server",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: ["Node.js", "Python"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    aiCapabilities: ["30,000+ Agent Actions", "Universal App Connectivity", "Natural Language Automation"],
    aiDifficulty: "AI-Native",
    starterPrompt: "Claude, use Zapier to add this new lead to my 'Sales Pipeline' Google Sheet.",
    mcpReady: true,
    isFeatured: true,
    alternativeTo: ["Make.com", "n8n", "Tray.io"],
  },
  {
    slug: "make-com",
    name: "Make.com",
    oneLiner: "Visual automation platform with powerful agentic capabilities.",
    description:
      "Make (formerly Integromat) is a visual platform for building complex automations. Its official MCP server turns Make scenarios into tools that AI agents can trigger on-demand. This is ideal for sales teams that have complex, multi-step backend processes that need to be initiated via a chat interface. Make offers more granular control than Zapier, making it a favorite for technical AI-native operators.",
    category: "Workflow Automation",
    logoUrl: "/logos/make.svg",
    websiteUrl: "https://www.make.com",
    docsUrl: "https://www.make.com/en/help/mcp",
    pricingUrl: "https://www.make.com/en/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [
      {
        platform: "MCP",
        url: "https://github.com/make-com/mcp-server",
        label: "Official MCP Server",
      },
    ],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    aiCapabilities: ["Trigger Scenarios via AI", "Complex Backend Orchestration", "Agentic Tool Creation"],
    aiDifficulty: "Technical",
    starterPrompt: "Claude, run the 'Lead Enrichment' scenario in Make for the company 'Acme.com'.",
    mcpReady: true,
    isFeatured: false,
    alternativeTo: ["Zapier", "n8n", "Apideck"],
  },
]

export const categories: CategoryMeta[] = [
  {
    slug: "prospecting",
    name: "Prospecting",
    description:
      "Empower your AI agents to find, verify, and build high-intent lead lists. These tools provide the raw data needed to feed your automated sales engine.",
    icon: "Search",
    toolCount: 14,
  },
  {
    slug: "email-outreach",
    name: "Email Outreach",
    description:
      "Give your AI the 'hands' to send personalized emails at scale. These APIs handle deliverability and sequences so your agent can focus on closing.",
    icon: "Mail",
    toolCount: 5,
  },
  {
    slug: "crm",
    name: "CRM",
    description:
      "The source of truth for your AI. Connect these APIs to let your agent manage deals, update contact status, and map relationships automatically.",
    icon: "Users",
    toolCount: 7,
  },
  {
    slug: "enrichment",
    name: "Enrichment",
    description:
      "Upgrade your data with AI. These APIs augment raw lead records with firmographic and technographic signals for better personalization.",
    icon: "Database",
    toolCount: 5,
  },
  {
    slug: "voice-and-calling",
    name: "Voice & Calling",
    description:
      "Deploy AI voice agents that can make calls, handle support, and set appointments. Transform your terminal into a call center.",
    icon: "Phone",
    toolCount: 4,
  },
  {
    slug: "scheduling",
    name: "Scheduling",
    description:
      "Let AI handle the back-and-forth. These APIs allow your agents to book meetings and manage availability directly within any chat workflow.",
    icon: "Calendar",
    toolCount: 3,
  },
  {
    slug: "conversation-intelligence",
    name: "Conversation Intelligence",
    description:
      "Turn meetings into actionable data. Use these APIs to let your AI transcribe, summarize, and extract insights from every customer call.",
    icon: "MessageSquare",
    toolCount: 3,
  },
  {
    slug: "documents-and-proposals",
    name: "Documents & Proposals",
    description:
      "Automate the closing process. These APIs let your AI generate, send, and track proposals and contracts without manual effort.",
    icon: "FileText",
    toolCount: 1,
  },
  {
    slug: "sales-engagement",
    name: "Sales Engagement",
    description:
      "Orchestrate multi-channel sequences. Use these tools to let your AI manage touchpoints across email, phone, and social in one place.",
    icon: "Zap",
    toolCount: 2,
  },
  {
    slug: "workflow-automation",
    name: "Workflow Automation",
    description:
      "The glue for your AI stack. Connect disparate sales tools and build complex, multi-step automations triggered by any event.",
    icon: "GitBranch",
    toolCount: 5,
  },
]
