import type { SalesTool, CategoryMeta } from "./types"

export const tools: SalesTool[] = [
  // ── Prospecting ──────────────────────────────────────────────
  {
    slug: "apollo",
    name: "Apollo.io",
    oneLiner: "Sales intelligence and engagement platform with a massive B2B contact database.",
    description:
      "Apollo.io provides a REST API that gives developers programmatic access to over 275 million verified contacts and 60 million companies. Build prospecting workflows, enrich leads in real time, and sync data directly into your CRM. The API supports advanced search filters, email sequencing, and engagement tracking, making it ideal for teams that want to automate top-of-funnel pipeline generation.",
    category: "Prospecting",
    logoUrl: "/logos/apollo.svg",
    websiteUrl: "https://www.apollo.io",
    docsUrl: "https://apolloio.github.io/apollo-api-docs/",
    pricingUrl: "https://www.apollo.io/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js"],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    isFeatured: true,
    alternativeTo: ["ZoomInfo", "Lusha", "Cognism"],
  },
  {
    slug: "clay",
    name: "Clay",
    oneLiner: "Creative data enrichment and outbound automation platform.",
    description:
      "Clay's REST API lets you programmatically run waterfall enrichment across 100+ data providers, build dynamic lead lists, and orchestrate personalized outbound campaigns. It acts as a universal connector between data sources so you can enrich any prospect record with firmographic, technographic, and intent signals. Clay is a go-to tool for revenue teams building highly targeted, data-driven outreach at scale.",
    category: "Prospecting",
    logoUrl: "/logos/clay.svg",
    websiteUrl: "https://www.clay.com",
    docsUrl: "https://docs.clay.com",
    pricingUrl: "https://www.clay.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    isFeatured: true,
    alternativeTo: ["Apollo.io", "ZoomInfo", "Clearbit"],
  },
  {
    slug: "prospeo",
    name: "Prospeo",
    oneLiner: "Email finder and verification API for sales prospecting.",
    description:
      "Prospeo offers a straightforward REST API for finding and verifying professional email addresses at scale. Use the email finder to locate contacts by name and domain, run bulk verification to clean your lists, and extract emails from LinkedIn profiles. Prospeo is designed for lean sales teams and developers who need reliable email discovery without the overhead of a full-suite platform.",
    category: "Prospecting",
    logoUrl: "/logos/prospeo.svg",
    websiteUrl: "https://prospeo.io",
    docsUrl: "https://prospeo.io/api/documentation",
    pricingUrl: "https://prospeo.io/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Hunter.io", "Snov.io"],
  },

  // ── Email Outreach ───────────────────────────────────────────
  {
    slug: "instantly",
    name: "Instantly.ai",
    oneLiner: "Cold email infrastructure and outreach automation at scale.",
    description:
      "Instantly.ai provides a REST API for managing cold email campaigns, warming up inboxes, and tracking deliverability metrics programmatically. Developers can create and schedule multi-step email sequences, manage unlimited sending accounts, and pull analytics on open rates, replies, and bounces. It is built for agencies and sales teams that need to scale outbound email without sacrificing deliverability.",
    category: "Email Outreach",
    logoUrl: "/logos/instantly.svg",
    websiteUrl: "https://instantly.ai",
    docsUrl: "https://developer.instantly.ai",
    pricingUrl: "https://instantly.ai/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Lemlist", "Smartlead", "Woodpecker"],
  },
  {
    slug: "resend",
    name: "Resend",
    oneLiner: "Modern email API built for developers.",
    description:
      "Resend is a developer-first email API that makes sending transactional and marketing emails simple and reliable. The REST API supports sending emails with React components as templates, domain verification, audience management, and detailed delivery analytics. With SDKs for Python, Node.js, Go, and Ruby, Resend is ideal for SaaS teams that want to own their email infrastructure with minimal setup.",
    category: "Email Outreach",
    logoUrl: "/logos/resend.svg",
    websiteUrl: "https://resend.com",
    docsUrl: "https://resend.com/docs",
    pricingUrl: "https://resend.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js", "Go", "Ruby"],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["SendGrid", "Postmark", "Mailgun"],
  },
  {
    slug: "loops",
    name: "Loops",
    oneLiner: "Email platform for modern SaaS companies.",
    description:
      "Loops provides a REST API for sending transactional emails, managing contacts, and triggering event-based email campaigns. It is designed specifically for SaaS companies that need to combine marketing loops, onboarding sequences, and product emails in one platform. The API is clean and well-documented, making it easy to integrate lifecycle email into your application.",
    category: "Email Outreach",
    logoUrl: "/logos/loops.svg",
    websiteUrl: "https://loops.so",
    docsUrl: "https://loops.so/docs/api",
    pricingUrl: "https://loops.so/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: ["Node.js"],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Customer.io", "Mailchimp", "Resend"],
  },

  // ── CRM ──────────────────────────────────────────────────────
  {
    slug: "attio",
    name: "Attio",
    oneLiner: "Next-generation CRM with a powerful, flexible API.",
    description:
      "Attio is a modern CRM that exposes a comprehensive REST API for managing contacts, companies, deals, and custom objects. The API supports complex filtering, real-time webhooks, and full CRUD on all data models. Attio also offers an official MCP server, making it one of the first CRMs to support the Model Context Protocol for AI-powered integrations.",
    category: "CRM",
    logoUrl: "/logos/attio.svg",
    websiteUrl: "https://attio.com",
    docsUrl: "https://developers.attio.com",
    pricingUrl: "https://attio.com/pricing",
    apiType: ["REST"],
    authMethod: ["OAuth2", "Bearer Token"],
    integrations: [{ platform: "MCP", url: "https://github.com/attio/mcp-server", label: "Official MCP Server" }],
    hasFreeTier: true,
    sdkLanguages: ["Node.js"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://developers.attio.com/reference/openapi-spec",
    isFeatured: false,
    alternativeTo: ["HubSpot", "Salesforce", "Folk"],
  },
  {
    slug: "twenty",
    name: "Twenty",
    oneLiner: "Open-source CRM with REST and GraphQL APIs.",
    description:
      "Twenty is an open-source CRM that offers both REST and GraphQL APIs for full control over your customer data. Self-host it or use the cloud version to manage contacts, companies, opportunities, and custom objects. The GraphQL API provides flexible querying, while the REST API covers standard CRUD operations. As an open-source project, Twenty gives teams complete transparency and the ability to extend the platform.",
    category: "CRM",
    logoUrl: "/logos/twenty.svg",
    websiteUrl: "https://twenty.com",
    docsUrl: "https://twenty.com/developers",
    pricingUrl: "https://twenty.com/pricing",
    githubUrl: "https://github.com/twentyhq/twenty",
    apiType: ["REST", "GraphQL"],
    authMethod: ["API Key", "Bearer Token"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://twenty.com/developers/rest-api",
    isFeatured: false,
    alternativeTo: ["Salesforce", "HubSpot", "Attio"],
  },
  {
    slug: "hubspot",
    name: "HubSpot",
    oneLiner: "All-in-one CRM platform with an extensive API ecosystem.",
    description:
      "HubSpot offers one of the most comprehensive CRM APIs in the market, covering contacts, companies, deals, tickets, marketing, and custom objects. The REST API supports batch operations, advanced filtering with CRM search, and real-time webhooks. With official SDKs in Python, Node.js, Ruby, and PHP, plus an MCP server for AI integrations, HubSpot is the industry standard for CRM automation and is trusted by over 200,000 businesses worldwide.",
    category: "CRM",
    logoUrl: "/logos/hubspot.svg",
    websiteUrl: "https://www.hubspot.com",
    docsUrl: "https://developers.hubspot.com",
    pricingUrl: "https://www.hubspot.com/pricing",
    apiType: ["REST"],
    authMethod: ["OAuth2", "Bearer Token", "API Key"],
    integrations: [{ platform: "MCP", url: "https://github.com/hubspot/hubspot-mcp", label: "Official MCP Server" }],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js", "Ruby", "PHP"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://api.hubspot.com/api-catalog-public/v1/apis",
    isFeatured: true,
    alternativeTo: ["Salesforce", "Attio", "Pipedrive"],
  },
  {
    slug: "folk",
    name: "Folk",
    oneLiner: "Lightweight CRM designed for relationship-driven teams.",
    description:
      "Folk is a collaborative CRM with a REST API that lets you manage contacts, companies, and pipelines programmatically. The API supports creating and updating records, managing custom fields, and syncing data from external sources. Folk is built for teams that prioritize relationships over rigid sales processes, making it popular with VCs, agencies, and partnership teams.",
    category: "CRM",
    logoUrl: "/logos/folk.svg",
    websiteUrl: "https://www.folk.app",
    docsUrl: "https://developers.folk.app",
    pricingUrl: "https://www.folk.app/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Attio", "HubSpot", "Streak"],
  },

  // ── Enrichment ───────────────────────────────────────────────
  {
    slug: "clearbit",
    name: "Clearbit (Breeze)",
    oneLiner: "Real-time company and person enrichment API by HubSpot.",
    description:
      "Clearbit, now part of HubSpot as Breeze Intelligence, provides REST APIs for enriching person and company records in real time. Look up any email or domain to get firmographic data, technographics, employee counts, funding details, and more. The Enrichment API powers lead scoring, routing, and personalization for thousands of B2B companies and integrates natively with HubSpot CRM.",
    category: "Enrichment",
    logoUrl: "/logos/clearbit.svg",
    websiteUrl: "https://clearbit.com",
    docsUrl: "https://dashboard.clearbit.com/docs",
    pricingUrl: "https://clearbit.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key", "Bearer Token"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: ["Node.js", "Python"],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["People Data Labs", "ZoomInfo", "Apollo.io"],
  },
  {
    slug: "people-data-labs",
    name: "People Data Labs",
    oneLiner: "B2B data API with 3 billion person and company records.",
    description:
      "People Data Labs provides a REST API for accessing one of the largest people and company datasets available. Use the Person Enrichment, Company Enrichment, and Search APIs to build prospecting lists, enrich CRM records, and power data-driven applications. With SDKs in Python, Node.js, Go, and Ruby, PDL is designed for developers building data products and go-to-market tools at scale.",
    category: "Enrichment",
    logoUrl: "/logos/people-data-labs.svg",
    websiteUrl: "https://www.peopledatalabs.com",
    docsUrl: "https://docs.peopledatalabs.com",
    pricingUrl: "https://www.peopledatalabs.com/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js", "Go", "Ruby"],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Clearbit", "ZoomInfo", "Apollo.io"],
  },
  {
    slug: "proxycurl",
    name: "Proxycurl",
    oneLiner: "API for scraping and enriching LinkedIn profile data.",
    description:
      "Proxycurl provides a REST API that extracts structured data from LinkedIn profiles and company pages without requiring a LinkedIn account or dealing with rate limits. Use it to enrich leads with job titles, work history, education, skills, and company details. Proxycurl is popular among sales and recruiting teams that need reliable LinkedIn data for prospecting and research workflows.",
    category: "Enrichment",
    logoUrl: "/logos/proxycurl.svg",
    websiteUrl: "https://nubela.co/proxycurl",
    docsUrl: "https://nubela.co/proxycurl/docs",
    pricingUrl: "https://nubela.co/proxycurl/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: ["Python"],
    hasWebhooks: false,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Clearbit", "People Data Labs", "PhantomBuster"],
  },

  // ── Voice & Calling ──────────────────────────────────────────
  {
    slug: "bland-ai",
    name: "Bland.ai",
    oneLiner: "AI phone calling API for sales and support automation.",
    description:
      "Bland.ai provides a REST API for making and receiving AI-powered phone calls at scale. Build automated outbound calling campaigns, inbound call handling, and conversational voice agents without managing telephony infrastructure. The API supports custom voice personas, call transfers, and real-time transcription, making it ideal for sales teams looking to automate qualification calls and appointment setting.",
    category: "Voice & Calling",
    logoUrl: "/logos/bland-ai.svg",
    websiteUrl: "https://www.bland.ai",
    docsUrl: "https://docs.bland.ai",
    pricingUrl: "https://www.bland.ai/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Vapi", "Retell.ai", "Air.ai"],
  },
  {
    slug: "vapi",
    name: "Vapi",
    oneLiner: "Developer platform for building voice AI agents.",
    description:
      "Vapi is a developer-first platform with a REST API for building, testing, and deploying voice AI agents. Create custom voice assistants that can make and receive phone calls, handle complex conversations, and integrate with your existing tools. Vapi supports multiple LLM providers, custom voices, function calling, and real-time streaming, giving developers full control over the voice AI experience.",
    category: "Voice & Calling",
    logoUrl: "/logos/vapi.svg",
    websiteUrl: "https://vapi.ai",
    docsUrl: "https://docs.vapi.ai",
    pricingUrl: "https://vapi.ai/pricing",
    apiType: ["REST"],
    authMethod: ["Bearer Token"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: ["Python", "Node.js"],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://docs.vapi.ai/api-reference/openapi-spec",
    isFeatured: true,
    alternativeTo: ["Bland.ai", "Retell.ai", "Twilio"],
  },

  // ── Scheduling ───────────────────────────────────────────────
  {
    slug: "cal-com",
    name: "Cal.com",
    oneLiner: "Open-source scheduling infrastructure with a full API.",
    description:
      "Cal.com is the open-source alternative to Calendly, offering a REST API for managing event types, bookings, availability, and users programmatically. Embed scheduling into your product, sync calendars, and automate booking workflows. As an open-source project, Cal.com gives you full control over your scheduling infrastructure, with options to self-host or use the managed cloud platform.",
    category: "Scheduling",
    logoUrl: "/logos/cal-com.svg",
    websiteUrl: "https://cal.com",
    docsUrl: "https://cal.com/docs/api-reference",
    pricingUrl: "https://cal.com/pricing",
    githubUrl: "https://github.com/calcom/cal.com",
    apiType: ["REST"],
    authMethod: ["API Key", "OAuth2"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://api.cal.com/v2/docs",
    isFeatured: true,
    alternativeTo: ["Calendly", "SavvyCal", "TidyCal"],
  },
  {
    slug: "calendly",
    name: "Calendly",
    oneLiner: "Scheduling automation platform with a robust API.",
    description:
      "Calendly's REST API allows developers to manage event types, list scheduled events, handle invitee data, and subscribe to real-time webhooks for booking notifications. Integrate Calendly into your sales workflow to automate meeting scheduling, route leads to the right reps, and sync booking data with your CRM. Calendly is the most widely adopted scheduling tool for sales and customer-facing teams.",
    category: "Scheduling",
    logoUrl: "/logos/calendly.svg",
    websiteUrl: "https://calendly.com",
    docsUrl: "https://developer.calendly.com",
    pricingUrl: "https://calendly.com/pricing",
    apiType: ["REST"],
    authMethod: ["OAuth2", "Bearer Token"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Cal.com", "SavvyCal", "Chili Piper"],
  },

  // ── Conversation Intelligence ────────────────────────────────
  {
    slug: "fireflies",
    name: "Fireflies.ai",
    oneLiner: "AI meeting assistant with transcription and analytics APIs.",
    description:
      "Fireflies.ai offers both REST and GraphQL APIs for accessing meeting transcripts, summaries, action items, and conversation analytics. Automatically record and transcribe meetings from Zoom, Google Meet, and Teams, then query the data programmatically. The GraphQL API is especially powerful for building custom dashboards and integrating meeting intelligence into your sales stack.",
    category: "Conversation Intelligence",
    logoUrl: "/logos/fireflies.svg",
    websiteUrl: "https://fireflies.ai",
    docsUrl: "https://docs.fireflies.ai",
    pricingUrl: "https://fireflies.ai/pricing",
    apiType: ["REST", "GraphQL"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: false,
    isFeatured: false,
    alternativeTo: ["Gong", "Chorus", "Otter.ai"],
  },
  {
    slug: "recall-ai",
    name: "Recall.ai",
    oneLiner: "Universal meeting bot API for real-time audio and video.",
    description:
      "Recall.ai provides a REST API that lets you deploy meeting bots to Zoom, Google Meet, Microsoft Teams, and other platforms to capture real-time audio, video, and transcription data. Build conversation intelligence, coaching tools, or compliance recording features without managing complex WebRTC or bot infrastructure. Recall.ai handles the heavy lifting of joining meetings and streaming media reliably.",
    category: "Conversation Intelligence",
    logoUrl: "/logos/recall-ai.svg",
    websiteUrl: "https://www.recall.ai",
    docsUrl: "https://docs.recall.ai",
    pricingUrl: "https://www.recall.ai/pricing",
    apiType: ["REST"],
    authMethod: ["API Key"],
    integrations: [],
    hasFreeTier: false,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://docs.recall.ai/reference",
    isFeatured: false,
    alternativeTo: ["Fireflies.ai", "Gong", "Assembly AI"],
  },

  // ── Workflow Automation ──────────────────────────────────────
  {
    slug: "n8n",
    name: "n8n",
    oneLiner: "Open-source workflow automation with a powerful API.",
    description:
      "n8n is an open-source workflow automation platform with a REST API for managing workflows, executions, and credentials programmatically. Build complex sales automations by connecting 400+ integrations, trigger workflows via webhooks, and monitor execution history through the API. Self-host n8n for full control or use the cloud version for managed infrastructure.",
    category: "Workflow Automation",
    logoUrl: "/logos/n8n.svg",
    websiteUrl: "https://n8n.io",
    docsUrl: "https://docs.n8n.io/api/",
    pricingUrl: "https://n8n.io/pricing",
    githubUrl: "https://github.com/n8n-io/n8n",
    apiType: ["REST"],
    authMethod: ["API Key", "Basic Auth"],
    integrations: [],
    hasFreeTier: true,
    sdkLanguages: [],
    hasWebhooks: true,
    hasOpenApiSpec: true,
    openApiSpecUrl: "https://docs.n8n.io/api/api-reference/",
    isFeatured: false,
    alternativeTo: ["Zapier", "Make", "Tray.io"],
  },
]

export const categories: CategoryMeta[] = [
  {
    slug: "prospecting",
    name: "Prospecting",
    description:
      "APIs and tools for finding, verifying, and building lists of potential customers. Prospecting tools give you access to B2B contact databases, email finders, and lead scoring engines to fill your pipeline with qualified prospects.",
    icon: "Search",
    toolCount: 3,
  },
  {
    slug: "email-outreach",
    name: "Email Outreach",
    description:
      "APIs for sending cold emails, transactional messages, and automated email sequences at scale. These tools handle deliverability, inbox warm-up, and campaign analytics so you can focus on writing great copy.",
    icon: "Mail",
    toolCount: 3,
  },
  {
    slug: "crm",
    name: "CRM",
    description:
      "Customer Relationship Management APIs for managing contacts, companies, deals, and pipelines. CRM APIs let you build custom integrations, sync data across tools, and automate your sales processes.",
    icon: "Users",
    toolCount: 4,
  },
  {
    slug: "enrichment",
    name: "Enrichment",
    description:
      "Data enrichment APIs that augment your lead and customer records with firmographic, technographic, and demographic data. Use enrichment tools to score leads, personalize outreach, and keep your CRM data fresh.",
    icon: "Database",
    toolCount: 3,
  },
  {
    slug: "voice-and-calling",
    name: "Voice & Calling",
    description:
      "APIs for building AI-powered voice agents, automating phone calls, and managing telephony infrastructure. Voice and calling tools enable automated outbound dialing, inbound call handling, and real-time transcription.",
    icon: "Phone",
    toolCount: 2,
  },
  {
    slug: "scheduling",
    name: "Scheduling",
    description:
      "Scheduling APIs for automating appointment booking, managing availability, and embedding calendars into your product. These tools eliminate back-and-forth emails and streamline the meeting booking process for sales teams.",
    icon: "Calendar",
    toolCount: 2,
  },
  {
    slug: "conversation-intelligence",
    name: "Conversation Intelligence",
    description:
      "APIs for recording, transcribing, and analyzing sales calls and meetings. Conversation intelligence tools surface insights, action items, and coaching opportunities from every customer interaction.",
    icon: "MessageSquare",
    toolCount: 2,
  },
  {
    slug: "documents-and-proposals",
    name: "Documents & Proposals",
    description:
      "APIs for generating, sending, and tracking sales proposals, contracts, and documents. Automate document workflows, collect e-signatures, and monitor engagement to close deals faster.",
    icon: "FileText",
    toolCount: 0,
  },
  {
    slug: "sales-engagement",
    name: "Sales Engagement",
    description:
      "APIs for orchestrating multi-channel sales sequences across email, phone, and social. Sales engagement platforms help reps follow up consistently and track prospect interactions across every touchpoint.",
    icon: "Zap",
    toolCount: 0,
  },
  {
    slug: "workflow-automation",
    name: "Workflow Automation",
    description:
      "APIs for building automated workflows that connect your sales stack. Workflow automation tools let you trigger actions across apps, sync data in real time, and eliminate manual processes from your revenue operations.",
    icon: "GitBranch",
    toolCount: 1,
  },
]
