export interface Skill {
  slug: string
  name: string
  description: string
  category: "Outreach" | "Research" | "CRM" | "Analytics" | "Operations" | "Enablement" | "Claude Plugins"
  difficulty: "Beginner" | "Intermediate" | "Advanced"
  worksWithTools: string[]
  promptContent: string
  source: string
  sourceUrl?: string
  installCommand?: string
}

const skills: Skill[] = [
  {
    slug: "apollo-outreach",
    name: "Apollo Outreach",
    description: "Research and enrich B2B leads using the Apollo.io API. Find leads, prospect research, company enrichment, and decision makers.",
    category: "Outreach",
    difficulty: "Intermediate",
    worksWithTools: ["apollo"],
    promptContent: "",
    source: "robertbstillwell",
    sourceUrl: "https://github.com/robertbstillwell/marketing-skills",
    installCommand: "npx add-skill robertbstillwell/marketing-skills",
  },
  {
    slug: "sales-outreach",
    name: "Sales Outreach",
    description: "ABM email personalization, cold outreach drafting, and professional tone frameworks for B2B sales.",
    category: "Outreach",
    difficulty: "Intermediate",
    worksWithTools: ["apollo", "linkedin", "exa-ai"],
    promptContent: "",
    source: "arielperez82",
    sourceUrl: "https://github.com/arielperez82/agents-and-skills",
    installCommand: "npx add-skill arielperez82/agents-and-skills",
  },
  {
    slug: "apollo-core-workflow",
    name: "Apollo Core Workflow",
    description: "Implement Apollo.io lead search and enrichment workflow. Build lead generation features, search contacts, and enrich prospect data.",
    category: "Operations",
    difficulty: "Intermediate",
    worksWithTools: ["apollo"],
    promptContent: "",
    source: "nivkazdan",
    sourceUrl: "https://github.com/nivkazdan/skills-agents-catalog",
    installCommand: "npx add-skill nivkazdan/skills-agents-catalog",
  },
  {
    slug: "marketing-leads-generation",
    name: "Marketing Leads Generation",
    description: "Generate and qualify marketing leads with AI. Build targeted prospect lists for outreach campaigns.",
    category: "Operations",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "FastMCP",
    sourceUrl: "https://fastmcp.me/Skills/Details/385/marketing-leads-generation",
    installCommand: "mkdir -p .claude/skills/marketing-leads-generation && curl -L -o skill.zip \"https://fastmcp.me/Skills/Download/385\" && unzip -o skill.zip -d .claude/skills/marketing-leads-generation && rm skill.zip",
  },
  {
    slug: "sales-ai-agents",
    name: "Sales AI Agents",
    description: "AI-powered sales automation agents that identify stale deals in HubSpot and generate personalized follow-up emails. Also finds high-engagement Marketing Contacts without deals for re-engagement outreach.",
    category: "Outreach",
    difficulty: "Advanced",
    worksWithTools: ["hubspot", "anthropic-claude", "slack", "fireflies", "apollo"],
    promptContent: "",
    source: "sneurgaonkar",
    sourceUrl: "https://github.com/sneurgaonkar/sales-ai-agents",
    installCommand: "git clone https://github.com/sneurgaonkar/sales-ai-agents.git",
  },
  {
    slug: "salesably-marketplace",
    name: "Salesably Marketplace",
    description: "Claude Code plugins for sales and marketing teams. Includes 10 marketing skills (brand voice, positioning, content strategy, copywriting) and 9 sales skills (deal qualification, prospect research, call preparation).",
    category: "Operations",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "Salesably",
    sourceUrl: "https://github.com/Salesably/salesably-marketplace",
    installCommand: "/plugin marketplace add Salesably/salesably-marketplace && /plugin install marketing-skills && /plugin install sales-skills",
  },
  {
    slug: "goose-skills",
    name: "Goose Skills",
    description: "Library of 125 GTM skills for Claude Code. Includes skills for ads, brand, competitive intel, content, lead generation, monitoring, outreach, research, and SEO. Features 55 atomic capabilities, 61 composite chains, and 9 playbooks.",
    category: "Operations",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "athina-ai",
    sourceUrl: "https://github.com/athina-ai/goose-skills",
    installCommand: "npx goose-skills install <slug>",
  },
  {
    slug: "openclaw-skills",
    name: "OpenClaw Skills Collection",
    description: "Collection of OpenClaw skills for sales, outreach, and GTM automation. Browse and install individual skills from the collection.",
    category: "Operations",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "VoltAgent",
    sourceUrl: "https://github.com/VoltAgent/awesome-openclaw-skills",
    installCommand: "git clone https://github.com/VoltAgent/awesome-openclaw-skills.git ~/.claude/skills/openclaw",
  },
  {
    slug: "agent-gtm-skills",
    name: "Agent GTM Skills",
    description: "18 AI agent skills for go-to-market across strategy, outbound, inbound, paid, retention, and operations. 9,800+ lines covering positioning, ICP, pricing, cold outreach, AI SDR, lead enrichment, SEO, UGC ads, launches, and more. 2025-2026 benchmarks.",
    category: "Operations",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "chadboyda",
    sourceUrl: "https://github.com/chadboyda/agent-gtm-skills",
    installCommand: "npx add-skill chadboyda/agent-gtm-skills",
  },
  {
    slug: "lemlist-claude-skills",
    name: "Lemlist Claude Skills",
    description: "38 GTM, outbound, and revenue-ops skills for Claude Code — covering ICP definition, persona research, company analysis, competitor mapping, trigger-finding, list building, campaign design, copywriting (first-touch, follow-up, IC/manager/VP sequences), LinkedIn outreach, cold call scripts, pipeline analysis, reply handling, CRM dedup, n8n workflow building, and more. Built on empirical data from 244K+ campaigns and 249M+ emails.",
    category: "Operations",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "l3mpire",
    sourceUrl: "https://github.com/l3mpire/claude-skills",
    installCommand: "npx github:l3mpire/claude-skills",
  },
  // ── Claude Code Plugins ─────────────────────────────────────────
  {
    slug: "anthropic-sales-plugin",
    name: "Anthropic Sales Plugin",
    description: "Official Anthropic sales plugin — research prospects, prep for calls, process call notes, build interactive battlecards, generate sales assets, draft personalized outreach, and analyze pipeline with forecasts. Connects to CRM, Slack, email, and meeting tools via MCP.",
    category: "Claude Plugins",
    difficulty: "Beginner",
    worksWithTools: ["hubspot", "slack", "close", "clay", "zoominfo"],
    promptContent: "",
    source: "Anthropic",
    sourceUrl: "https://github.com/anthropics/knowledge-work-plugins",
    installCommand: "npx claudepluginhub anthropics/knowledge-work-plugins --plugin sales",
  },
  {
    slug: "leadmagic-gtm-skills",
    name: "LeadMagic GTM Skills",
    description: "205 production GTM agent skills across 25 categories — sales, outbound, prospecting, RevOps, ABM, PLG, customer success, analytics, and automation. Each skill includes framework-cited playbooks, templates, and QA scripts. Curated bundles for outbound, prospecting, founder GTM, and more.",
    category: "Claude Plugins",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "LeadMagic",
    sourceUrl: "https://github.com/LeadMagic/gtm-skills",
    installCommand: "/plugin marketplace add LeadMagic/gtm-skills && /plugin install gtm-skills@gtm-skills",
  },
  {
    slug: "apollo-plugin",
    name: "Apollo.io Plugin",
    description: "Search, enrich, and sequence leads within Apollo.io — prospect by ICP in plain English, enrich contacts from sparse identifiers, bulk-add to outreach sequences, and query sales analytics. Official Apollo MCP plugin in the Anthropic marketplace.",
    category: "Claude Plugins",
    difficulty: "Beginner",
    worksWithTools: ["apollo"],
    promptContent: "",
    source: "Apollo.io",
    sourceUrl: "https://github.com/apolloio/apollo-mcp-plugin",
    installCommand: "npx claudepluginhub apolloio/apollo-mcp-plugin --plugin apollo",
  },
  {
    slug: "zoominfo-plugin",
    name: "ZoomInfo Plugin",
    description: "Official ZoomInfo MCP plugin — search 100M companies and 300M contacts, enrich leads with firmographics and technographics, find similar accounts, build targeted contact lists from natural language criteria, and get AI-ranked prospect recommendations.",
    category: "Claude Plugins",
    difficulty: "Beginner",
    worksWithTools: ["zoominfo"],
    promptContent: "",
    source: "ZoomInfo",
    sourceUrl: "https://github.com/Zoominfo/zoominfo-mcp-plugin",
    installCommand: "npx claudepluginhub Zoominfo/zoominfo-mcp-plugin --plugin zoominfo",
  },
  {
    slug: "zapier-gtm-cheat-codes",
    name: "Zapier GTM Cheat Codes",
    description: "Agent skills for GTM teams by Zapier — campaign planning, CRM context triage, customer advocacy, sales RevOps, content ops, and lead classification. Pre-built workflows with human approval gates connecting 8,000+ apps via Zapier MCP.",
    category: "Claude Plugins",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "Zapier",
    sourceUrl: "https://github.com/zapier/gtm-cheat-codes",
    installCommand: "git clone https://github.com/zapier/gtm-cheat-codes.git",
  },
  {
    slug: "manojbajaj-gtm-skills",
    name: "manojbajaj95 GTM Skills",
    description: "54 GTM skills across SEO & AI search, content marketing, outbound, sales, growth, analytics, strategy, ads, social, and CRM. Includes a bootstrap skill that interviews you about your brand and generates a structured project folder so every skill writes in your voice.",
    category: "Claude Plugins",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "manojbajaj95",
    sourceUrl: "https://github.com/manojbajaj95/claude-gtm-plugin",
    installCommand: "/plugin marketplace add manojbajaj95/claude-gtm-plugin && /plugin install gtm-skills@gtm-plugins",
  },
  {
    slug: "octave-gtm-plugin",
    name: "Octave GTM Plugin",
    description: "Access Octave's GTM knowledge base from Claude Code — ICP definitions, buyer personas, competitive positioning, messaging, proof points, and objections. Generate positioning docs, research briefs, battlecards, and campaign assets grounded in your actual GTM strategy.",
    category: "Claude Plugins",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "Octave",
    sourceUrl: "https://github.com/octavehq/lfgtm",
    installCommand: "git clone https://github.com/octavehq/lfgtm.git",
  },
  {
    slug: "sales-enablement-plugin",
    name: "Sales Enablement Plugin",
    description: "18 skills, 7 slash commands, 16 MCP tools — self-healing content that flags itself when stale, persistent memory that learns from every deal, and pre-configured connectors for HubSpot, Gong, ZoomInfo, Clay, LinkedIn, Slack, Notion, and Fireflies. Ships with its own Sales Intelligence MCP server.",
    category: "Claude Plugins",
    difficulty: "Advanced",
    worksWithTools: ["hubspot", "slack", "zoominfo", "clay", "gong", "notion"],
    promptContent: "",
    source: "jbalbu01",
    sourceUrl: "https://github.com/jbalbu01/sales-enablement-plugin",
    installCommand: "claude plugins add sales-enablement-plugin",
  },
  {
    slug: "amplemarket-skills",
    name: "Amplemarket Skills",
    description: "37 sales and GTM skills for AI agents — account research, pipeline review, call coaching, deliverability monitoring, personalized outreach, and account penetration with deep research and strategic planning. Requires the Amplemarket MCP server.",
    category: "Claude Plugins",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "Amplemarket",
    sourceUrl: "https://github.com/amplemarket/skills",
    installCommand: "git clone https://github.com/amplemarket/skills.git",
  },
  {
    slug: "gtmvp-gtm-agents",
    name: "GTMVP GTM Agents",
    description: "18 GTM intelligence agents, 6 framework skills, and 5 slash commands for Claude Code — competitor mapping, positioning, channel strategy, attribution, conversion analysis, and brand strategy. 67 specialized plugins covering the full GTM stack.",
    category: "Claude Plugins",
    difficulty: "Advanced",
    worksWithTools: [],
    promptContent: "",
    source: "GTMVP",
    sourceUrl: "https://github.com/gtmagents/gtm-agents",
    installCommand: "/plugin marketplace add gtmagents/gtm-agents && /plugin install sales-prospecting",
  },
  {
    slug: "sales-revops-marketing",
    name: "Sales-RevOps-Marketing Agent",
    description: "14 product skills, 5 autonomous agents, 4 jurisdiction overlays — prospect research, lead scoring, outreach sequences, pipeline analysis, content creation, campaign planning, and automated RevOps dashboards across US, EU, Pakistan, and GCC markets.",
    category: "Claude Plugins",
    difficulty: "Advanced",
    worksWithTools: [],
    promptContent: "",
    source: "Panaversity",
    sourceUrl: "https://github.com/panaversity/agentfactory-business-plugins",
    installCommand: "/plugin marketplace add panaversity/agentfactory-business-plugins && /plugin install sales-revops-marketing",
  },
  {
    slug: "extruct-gtm-skills",
    name: "Extruct AI GTM Skills",
    description: "21 GTM skills for building and executing outbound campaigns — research target accounts and verticals, build and enrich contact lists, draft personalized outreach sequences, simulate prospect reactions, validate emails, and manage campaign sending via APIs.",
    category: "Claude Plugins",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "Extruct AI",
    sourceUrl: "https://github.com/extruct-ai/gtm-skills",
    installCommand: "git clone https://github.com/extruct-ai/gtm-skills.git",
  },
  {
    slug: "amplitude-growth-skills",
    name: "Amplitude Growth Skills",
    description: "Official Amplitude plugin with growth skills for activation analysis, retention optimization, funnel diagnosis, monetization, acquisition channel assessment, and GTM metric trees. Also includes sales skills, product skills, and launch skills. Battle-tested by PMs and GTM teams at Amplitude. 50+ skills across 8 sub-plugins.",
    category: "Claude Plugins",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "Amplitude",
    sourceUrl: "https://github.com/amplitude/builder-skills",
    installCommand: "/plugin marketplace add amplitude/builder-skills && /plugin install growth-skills@builder-skills",
  },
  {
    slug: "minimalist-entrepreneur",
    name: "Minimalist Entrepreneur",
    description: "10 skills based on The Minimalist Entrepreneur by Sahil Lavingia (Gumroad founder). Find community, validate ideas, build MVPs, processize, find first customers, set pricing, create marketing plans, grow sustainably, define company values, and gut-check decisions. Follows the book's progression from community to scale.",
    category: "Claude Plugins",
    difficulty: "Beginner",
    worksWithTools: [],
    promptContent: "",
    source: "Sahil Lavingia",
    sourceUrl: "https://github.com/slavingia/skills",
    installCommand: "/plugin marketplace add slavingia/skills && /plugin install minimalist-entrepreneur",
  },
  {
    slug: "growth-skills-pfoy",
    name: "Growth Skills (197 GTM Playbooks)",
    description: "197 production-grade GTM playbooks across 16 categories — content (75), outbound (56), inbound (22), sequencing tools (21), ABM (20), CRM (19), analytics (19), AI agents (18), enrichment (14), sales plays (13), qualification (13), lifecycle (13), demand gen (7), operations (7), partnerships (3), and events (3). Written by operators, maintained by Growth Engineer.",
    category: "Claude Plugins",
    difficulty: "Intermediate",
    worksWithTools: [],
    promptContent: "",
    source: "Growth Engineer",
    sourceUrl: "https://github.com/pfoy/growth-skills",
    installCommand: "/plugin marketplace add pfoy/growth-skills && /plugin install growth-skills@growthengineer",
  },
  {
    slug: "composio-lead-research",
    name: "Composio Lead Research Assistant",
    description: "Identifies and qualifies high-quality leads by analyzing your product, searching for target companies, and providing actionable outreach strategies. Part of the 67k-star awesome-claude-skills collection by Composio. Also includes automation skills for HubSpot, Salesforce, Close, Pipedrive, and Zoho CRM.",
    category: "Claude Plugins",
    difficulty: "Beginner",
    worksWithTools: [],
    promptContent: "",
    source: "ComposioHQ",
    sourceUrl: "https://github.com/ComposioHQ/awesome-claude-skills",
    installCommand: "git clone https://github.com/ComposioHQ/awesome-claude-skills.git && cp -r lead-research-assistant ~/.config/claude-code/skills/",
  },
]

export function getAllSkills(): Skill[] {
  return [...skills].reverse()
}

export function getSkillBySlug(slug: string): Skill | undefined {
  return skills.find((s) => s.slug === slug)
}

export function getSkillSlugs(): string[] {
  return skills.map((s) => s.slug)
}

export function getSkillsByCategory(category: Skill["category"]): Skill[] {
  return skills.filter((s) => s.category === category)
}

export function getSkillsForTool(toolSlug: string): Skill[] {
  return skills.filter((s) => s.worksWithTools.includes(toolSlug))
}

